import localFont from "next/font/local";
import Navbar from "@/components/layout/Navbar";
import "./globals.css";
import Footer from "@/components/layout/Footer";

const lilacFont = localFont({
  src: "../public/gopher.otf",
  variable: "--font-lilac",
  display: "swap",
});

export const metadata = {
  title: "Dr. Maya Reynolds",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={lilacFont.variable}>
      <body>
        {children}
      </body>
    </html>
  );
}
